- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable specific version
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install python mysql dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
    - nodejs
    - mysql

- name: Create a user expense
  ansible.builtin.user:
    name: expense

- name: remove a directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: Make a directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: download backend code
  ansible.builtin.get_url:
    url: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: /tmp/{{ component }}.zip


- name: Unarchive a backend code that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: "{{ app_location }}"
    remote_src: yes

- name: install npm
  ansible.builtin.command: npm install -y
  args:
    chdir: "{{ app_location }}"

- name: copy backend service
  ansible.builtin.template:
    src: backend.{{ component }}.j2
    dest: /etc/systemd/system/{{ component }}.service

- name: import data into mysql
  community.mysql.mysql_db:
    login_user: "{{ login_user }}"
    login_password: "{{ mysql_connection_pass }}"
    login_host: "{{ mysql_login_hosts }}"
    state: import
    name: all
    target: /app/schema/{{ component }}.sql

- name: update {{ component }} service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable service
  ansible.builtin.service:
    name: "{{ component }}"
    state: started
    enabled: yes
