- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable specific version
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install python mysql dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
    - nodejs
    - mysql

- name: Create a user expense
  ansible.builtin.user:
    name: expense

- name: Import role to the play
  ansible.builtin.import_role:
    tags:
      - deployment
    name: common
    tasks_from: app-pre-req

- name: install npm
  ansible.builtin.command: npm install -y
  args:
    chdir: "{{ app_location }}"

- name: copy backend service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/{{ component }}.service

- name: import data into mysql
  community.mysql.mysql_db:
    login_user: "{{ login_user }}"
    login_password: "{{ mysql_connection_pass }}"
    login_host: "{{ mysql_login_hosts }}"
    state: import
    name: all
    target: /app/schema/{{ component }}.sql

- name: update {{ component }} service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable service
  ansible.builtin.service:
    tags:
      - deployment
    name: "{{ component }}"
    state: started
    enabled: yes
