- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: start and enable service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: restart nginx service
  ansible.builtin.service:
    name: nginx
    state: started

- name: Remove directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: absent

- name: make a directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: directory

- name: download frontend code
  ansible.builtin.get_url:
    url: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: unarchive frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: "{{ app_location }}"
    remote_src: yes

- name: copy expense conf
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted