- name: Remove directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: absent

- name: make a directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: directory

- name: download {{ component }} code
  ansible.builtin.get_url:
    url: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: /tmp/{{ component }}.zip

- name: unarchive {{ component }} code
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: "{{ app_location }}"
    remote_src: yes
